web/app.py
#!/usr/bin/python3
from flask import Flask, render_template
import requests
from models.brand import Brand
from models.work import Work
from web.dashboard import dashboard
from web.general import general_bp
from web.auth import auth_bp
from flask_login import LoginManager
from web.auth import api_url
from datetime import timedelta

app = Flask(__name__)
app.url_map.strict_slashes = False
# Replace with strong secret key in production
app.config["SECRET_KEY"] = "dev"
app.config["PERMANENT_SESSION_LIFETIME"] = timedelta(minutes=10)
app.register_blueprint(general_bp)
app.register_blueprint(auth_bp)
app.register_blueprint(dashboard)
login_manager = LoginManager()
login_manager.login_view = "auth.login"
login_manager.init_app(app)


@app.errorhandler(404)
def not_found(_):
    return render_template("errors/404.html")


@login_manager.user_loader
def load_user(token):
    """Reload user from token stored in session"""
    response = requests.get(
        "{}/reload_brand/current".format(api_url), auth=(token, "")
    )
    data = response.json()
    user = Brand(**data)
    user.works = [Work(**work) for work in data["works"]]

    return user


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)

web/dashboard/__init__.py
#!/usr/bin/python3
"""Initialize dashboard blueprint"""
from flask import Blueprint

dashboard = Blueprint("dashboard", __name__, url_prefix="/dashboard")

from web.dashboard.index import *
from web.dashboard.vixpert import *
from web.dashboard.works import *

web/general/__init__.py
#!/usr/bin/python3
"""Initialize general blueprint"""
from flask import Blueprint

general_bp = Blueprint('general', __name__)

from web.general.routes import *

web/general/routes.py
#!/usr/bin/python3
"""Routes for the general blueprint"""
from web.general import general_bp
from flask import flash, render_template
import uuid


@general_bp.route("/<handle>")
def brand(handle):
    """Return a brand's page"""
    return render_template("brand.html", cache_id=uuid.uuid4())


@general_bp.route("/")
def home():
    """Return the homepage"""
    return render_template("index.html", cache_id=uuid.uuid4())

web/templates/contact_mail.html
<!DOCTYPE html>
<html>
<!-- Variables: site_url, message, sender_name, reply_email -->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;" />
    <!--[if !mso]--><!-- -->
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,600,700' rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Quicksand:300,400,700' rel="stylesheet">
    <!-- <![endif]-->
	
	<style></style>
</head>


<body class="respond" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
    <!-- header -->
    <table border="0" width="100%" cellpadding="0" cellspacing="0" bgcolor="ffffff">

        <tr>
            <td align="center">
                <table border="0" align="center" width="590" cellpadding="0" cellspacing="0" class="container590">

                    <tr>
                        <td height="25" style="font-size: 25px; line-height: 25px;">&nbsp;</td>
                    </tr>

                    <tr>
                        <td align="center">

                            <table border="0" align="center" width="590" cellpadding="0" cellspacing="0"
                                class="container590">

                                <tr>
                                    <td align="center" height="70" style="height:70px;">
                                        <a href="{site_url}"
                                            style="display: block; border-style: none !important; border: 0 !important;font-weight: 700;text-decoration: none;font-size: 34px;color: #000;">
                                            Vitrine
                                        </a>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    <tr>
                        <td height="25" style="font-size: 25px; line-height: 25px;">&nbsp;</td>
                    </tr>

                </table>
            </td>
        </tr>
    </table>
    <!-- end header -->

    <!-- big image section -->
    <table border="0" width="100%" cellpadding="0" cellspacing="0" bgcolor="ffffff" class="bg_color">

        <tr>
            <td align="center">
                <table border="0" align="center" width="590" cellpadding="0" cellspacing="0" class="container590">
                    <tr>

                        <td align="center" class="section-img">
                            <a href="" style=" border-style: none !important; display: block; border: 0 !important;">
                                <img src="https://i.imgur.com/fS5ga94.png" style="display: block; width: 590px;"
                                    border="0" alt="" />
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td height="20" style="font-size: 20px; line-height: 20px;">&nbsp;</td>
                    </tr>
                    <tr>
                        <td align="center"
                            style="color: #343434; font-size: 24px; font-family: Quicksand, Calibri, sans-serif; font-weight:700;letter-spacing: 3px; line-height: 35px;"
                            class="main-header">


                            <div style="line-height: 35px">

                                Message from <span style="color: #5caad2;">{sender_name}</span>

                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td height="10" style="font-size: 10px; line-height: 10px;">&nbsp;</td>
                    </tr>

                    <tr>
                        <td align="center">
                            <table border="0" width="40" align="center" cellpadding="0" cellspacing="0"
                                bgcolor="eeeeee">
                                <tr>
                                    <td height="2" style="font-size: 2px; line-height: 2px;">&nbsp;</td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    <tr>
                        <td height="20" style="font-size: 20px; line-height: 20px;">&nbsp;</td>
                    </tr>

                    <tr>
                        <td align="center">
                            <table border="0" width="400" align="center" cellpadding="0" cellspacing="0"
                                class="container590">
                                <tr>
                                    <td align="center"
                                        style="color: #888888; font-size: 16px; font-family: 'Work Sans', Calibri, sans-serif; line-height: 24px;">

                                        <div style="line-height: 24px">
                                            {message}
                                        </div>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    <tr>
                        <td height="25" style="font-size: 25px; line-height: 25px;">&nbsp;</td>
                    </tr>

                    <tr>
                        <td align="center">
                            <table border="0" align="center" width="160" cellpadding="0" cellspacing="0"
                                bgcolor="5caad2">

                                <tr>
                                    <td height="10" style="font-size: 10px; line-height: 10px;">&nbsp;</td>
                                </tr>

                                <tr>
                                    <td align="center"
                                        style="color: #ffffff; font-size: 14px; font-family: 'Work Sans', Calibri, sans-serif; line-height: 26px;">


                                        <div style="line-height: 26px;">
                                            <a href="mailto:{reply_email}"
                                                style="color: #ffffff; text-decoration: none;">REPLY</a>
                                        </div>
                                    </td>
                                </tr>

                                <tr>
                                    <td height="10" style="font-size: 10px; line-height: 10px;">&nbsp;</td>
                                </tr>

                            </table>
                        </td>
                    </tr>


                </table>

            </td>
        </tr>

        <tr class="hide">
            <td height="25" style="font-size: 25px; line-height: 25px;">&nbsp;</td>
        </tr>
        <tr>
            <td height="40" style="font-size: 40px; line-height: 40px;">&nbsp;</td>
        </tr>

    </table>
    <!-- end section -->

    <!-- contact section -->
    <table border="0" width="100%" cellpadding="0" cellspacing="0" bgcolor="ffffff" class="bg_color">

        <tr class="hide">
            <td height="25" style="font-size: 25px; line-height: 25px;">&nbsp;</td>
        </tr>
        <tr>
            <td height="40" style="font-size: 40px; line-height: 40px;">&nbsp;</td>
        </tr>

        <tr>
            <td height="60" style="border-top: 1px solid #e0e0e0;font-size: 60px; line-height: 60px;">&nbsp;</td>
        </tr>

        <tr>
            <td align="center">
                <table border="0" align="center" width="590" cellpadding="0" cellspacing="0"
                    class="container590 bg_color">

                    <tr>
                        <td>
                            <table border="0" width="300" align="left" cellpadding="0" cellspacing="0"
                                style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"
                                class="container590">

                                <tr>
                                    <!-- logo -->
                                    <td align="left">
                                        <a href="{site_url}"
                                            style="display: block; border-style: none !important; border: 0 !important;font-weight: bold;text-decoration: none;font-size: 34px; color: #000;">
                                            Vitrine
                                        </a>
                                    </td>
                                </tr>

                                <tr>
                                    <td height="25" style="font-size: 25px; line-height: 25px;">&nbsp;</td>
                                </tr>

                                <tr>
                                    <td align="left"
                                        style="color: #888888; font-size: 14px; font-family: 'Work Sans', Calibri, sans-serif; line-height: 23px;"
                                        class="text_color">
                                        <div
                                            style="color: #333333; font-size: 14px; font-family: 'Work Sans', Calibri, sans-serif; font-weight: 600; mso-line-height-rule: exactly; line-height: 23px;">

                                            Email us: <br /> <a href="mailto:miracleagbosixtus@gmail.com"
                                                style="color: #888888; font-size: 14px; font-family: 'Hind Siliguri', Calibri, Sans-serif; font-weight: 400;">miracleagbosixtus@gmail.com</a>

                                        </div>
                                    </td>
                                </tr>

                            </table>

                            <table border="0" width="2" align="left" cellpadding="0" cellspacing="0"
                                style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"
                                class="container590">
                                <tr>
                                    <td width="2" height="10" style="font-size: 10px; line-height: 10px;"></td>
                                </tr>
                            </table>

                            <table border="0" width="200" align="right" cellpadding="0" cellspacing="0"
                                style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"
                                class="container590">

                                <tr>
                                    <td class="hide" height="45" style="font-size: 45px; line-height: 45px;">&nbsp;</td>
                                </tr>



                                <tr>
                                    <td height="15" style="font-size: 15px; line-height: 15px;">&nbsp;</td>
                                </tr>

                                <tr>
                                    <td>
                                        <table border="0" align="right" cellpadding="0" cellspacing="0">
                                            <tr>
                                                <td>
                                                    <a href="https://twitter.com/sixtusagbo"
                                                        style="display: block; border-style: none !important; border: 0 !important;">
                                                        <img width="24" border="0"
                                                            style="display: block;border-radius: 7px;"
                                                            src="https://i.imgur.com/LS08Auhb.jpg" alt="">
                                                    </a>
                                                </td>
                                                <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                                                <td>
                                                    <a href="https://linkedin.com/in/sixtusagbo"
                                                        style="display: block; border-style: none !important; border: 0 !important;">
                                                        <img width="24" border="0"
                                                            style="display: block;display: block;border-radius: 7px;"
                                                            src="https://i.imgur.com/mg8oOzZb.jpg" alt="">
                                                    </a>
                                                </td>
                                                <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                                                <td>
                                                    <a href="https://github.com/sixtusagbo"
                                                        style="display: block; border-style: none !important; border: 0 !important;">
                                                        <img width="24" border="0"
                                                            style="display: block;display: block;border-radius: 7px;"
                                                            src="https://i.imgur.com/bx8Rxtab.jpg" alt="">
                                                    </a>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>

                            </table>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>

        <tr>
            <td height="60" style="font-size: 60px; line-height: 60px;">&nbsp;</td>
        </tr>

    </table>
    <!-- end section -->

</body>

</html>

web/templates/contact_styles.html
    <style type="text/css">
        body {
            width: 100%;
            background-color: #ffffff;
            margin: 0;
            padding: 0;
            -webkit-font-smoothing: antialiased;
            mso-margin-top-alt: 0px;
            mso-margin-bottom-alt: 0px;
            mso-padding-alt: 0px 0px 0px 0px;
            font-family: "Quicksand", sans-serif;
        }

        p,
        h1,
        h2,
        h3,
        h4 {
            margin-top: 0;
            margin-bottom: 0;
            padding-top: 0;
            padding-bottom: 0;
        }

        span.preheader {
            display: none;
            font-size: 1px;
        }

        html {
            width: 100%;
        }

        table {
            font-size: 14px;
            border: 0;
        }

        /* ----------- responsivity ----------- */

        @media only screen and (max-width: 640px) {

            /*------ top header ------ */
            .main-header {
                font-size: 20px !important;
            }

            .main-section-header {
                font-size: 28px !important;
            }

            .show {
                display: block !important;
            }

            .hide {
                display: none !important;
            }

            .align-center {
                text-align: center !important;
            }

            .no-bg {
                background: none !important;
            }

            /*----- main image -------*/
            .main-image img {
                width: 440px !important;
                height: auto !important;
            }

            /* ====== divider ====== */
            .divider img {
                width: 440px !important;
            }

            /*-------- container --------*/
            .container590 {
                width: 440px !important;
            }

            .container580 {
                width: 400px !important;
            }

            .main-button {
                width: 220px !important;
            }

            /*-------- secions ----------*/
            .section-img img {
                width: 320px !important;
                height: auto !important;
            }

            .team-img img {
                width: 100% !important;
                height: auto !important;
            }
        }

        @media only screen and (max-width: 479px) {

            /*------ top header ------ */
            .main-header {
                font-size: 18px !important;
            }

            .main-section-header {
                font-size: 26px !important;
            }

            /* ====== divider ====== */
            .divider img {
                width: 280px !important;
            }

            /*-------- container --------*/
            .container590 {
                width: 280px !important;
            }

            .container590 {
                width: 280px !important;
            }

            .container580 {
                width: 260px !important;
            }

            /*-------- secions ----------*/
            .section-img img {
                width: 280px !important;
                height: auto !important;
            }
        }
    </style>
    <!-- [if gte mso 9]><style type=”text/css”>
        body {
        font-family: arial, sans-serif!important;
        }
        </style>
    <![endif]-->

web/templates/dashboard/home.html
{% extends "layouts/dashboard.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
        <div
          class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
          <h2 class="h2">Dashboard</h2>
          <div class="btn-toolbar mb-2 mb-md-0">
            {% if not user.is_new %}
            <a href="#" class="btn btn-primary me-3" data-bs-toggle="modal"
              data-bs-target="#addWorkModal">Add work</a>
            {% endif %}
            <h4>Hi, {{ user.handle }}</h4>
          </div>
        </div>

        <div class="content">
          {% include "partials/messages.html" %}

          {% if user.is_new %}
          <div class="alert alert-primary d-flex align-items-center fs-6" role="alert">
            <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Info:">
              <use xlink:href="#info-fill"/>
            </svg>
            If you have issues receiving contact emails, please check your spam and mark our message as not spam.
          </div>
          <p>
            The humble wizard of vitrine known as <span class="fst-italic">Vixpert</span> will take you through the
            process of setting up your profile.
          </p>

          <p>
            Get started with <a href="{{ url_for('dashboard.vixpert') }}"
              class="link-primary text-decoration-none fw-bold">vixpert</a>.
          </p>
          {% else %}
          <div class="row">
            {% for work in user.works|sort(attribute="title") %}
            <div class="col-lg-4 col-md-6">
              <div class="card mb-3 h-100">
                <img src="{{ work.image_url }}" alt="{{ work.title }}" class="img-fluid">
                <div class="card-body">
                  <div class="d-flex justify-content-between">
                    <h5 class="card-title">{{ work.title }}</h5>
                    <button type="button" class="btn btn-primary"
                      data-bs-toggle="modal" data-bs-target="#edit-work-{{ work.id }}">
                      Edit</button>
                  </div>
                  <p class="card-text">{{ work.description }}</p>
                </div>
              </div>
            </div>

        <!-- Edit Work Modal -->
        <div class="modal fade" id="edit-work-{{ work.id }}"
          data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
          aria-labelledby="edit-work-{{ work.id }}-label" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="edit-work-{{ work.id }}-label">Edit Work</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal"
                    aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <form class="row" method="POST"
                  action={{ url_for("dashboard.update_work", work_id=work.id) }}>
                  <div class="col-12">
                    <div class="mb-3">
                      <label for="title" class="form-label">Title</label>
                      <input type="text" class="form-control form-control-lg" id="title" name="title" value="{{ work.title }}">
                    </div>
                    <div class="mb-3">
                      <label for="description" class="form-label">Description</label>
                      <input type="text" class="form-control form-control-lg" id="description" name="description" value="{{ work.description }}">
                    </div>
                    <div class="mb-3">
                      <label for="image_url" class="form-label">Image Link</label>
                      <input type="text" class="form-control form-control-lg" id="image_url" name="image_url" value="{{ work.image_url }}">
                    </div>
                  </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-warning"
                  data-bs-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-success">Save</button>
                </form>
              </div>
            </div>
          </div>
        </div>
            {% else %}
              <p>
              Apparently, you've not added any of your brand's work. Improve your brand page by adding a <a href="#" data-bs-toggle="modal" data-bs-target="#addWorkModal">work</a>.
              </p>
            {% endfor %}
          </div>
          {% endif %}
        </div>
{% endblock %}

web/templates/layouts/auth.html
{% extends "layouts/base.html" %}

{% block body_attributes %}
 class="d-flex h-100 w-100 bg-black text-white" data-bs-spy="scroll" data-bs-target="#navScroll"
{% endblock %}

{% block body %}
  <div class="h-100 container-fluid">
    <div class="h-100 row d-flex align-items-stretch">

      <div class="col-12 col-md-7 col-lg-6 col-xl-5 d-flex align-items-start flex-column px-vw-5">

        <header class="mb-auto py-vh-2 col-12">
          <a class="navbar-brand pe-md-4 fs-4 col-12 col-md-auto text-center" href="/">
            <span class="ms-md-1 mt-1 fw-bold me-md-5 border-top border-bottom">Vitrine</span>
          </a>

        </header>
        <main class="mb-auto col-12">
          {% block content %}
          {% endblock %}
        </main>
      </div>

      <div class="col-12 col-md-5 col-lg-6 col-xl-7 gradient d-none d-md-block"></div>

    </div>

  </div>
{% endblock %}

web/templates/layouts/base.html
<!doctype html>
<html class="h-100" lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

  <!-- SEO Meta Tags -->
  <meta name="title" content="Vitrine" />
  <meta name="description" content="Showcase your brand" />
  <meta name="author" content="Sixtus Agbo Miracle" />

  <!-- Open Graph / Facebook -->
  <meta property="og:type" content="website" />
  <meta property="og:url" content="{{ url_for('general.home', _external=True) }}" />
  <meta property="og:title" content="Vitrine" />
  <meta property="og:description" content="Showcase your brand" />
  <meta property="twitter:image" content="{{ url_for('static', filename='images/banner.jpg', _external=True) }}" />

  <!-- Twitter -->
  <meta property="twitter:card" content="summary_large_image" />
  <meta property="twitter:url" content="{{ url_for('general.home') }}" />
  <meta property="twitter:title" content="Vitrine" />
  <meta property="twitter:description" content="Showcase your brand" />
  <meta property="twitter:image" content="{{ url_for('static', filename='images/banner.jpg', _external=True) }}" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}" type="image/x-icon" />

  <title>{% block title %}{% endblock %} | Vitrine</title>

  <link rel="stylesheet" href="{{ url_for('static', filename='styles/bootstrap.css') }}" />
  <link rel="stylesheet" href="{{ url_for('static', filename='styles/aos.css') }}" />
  <link rel="stylesheet" href="{{ url_for('static', filename='styles/guest.css') }}" />
  {% block styles %} {% endblock %}
</head>

<body {% block body_attributes %}{% endblock %}>
  {% block body %} {% endblock %}

  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="{{ url_for('static', filename='scripts/bootstrap.bundle.min.js') }}"></script>
  {% block scripts %} {% endblock %}
</body>

</html>

web/templates/layouts/general.html
{% extends "layouts/base.html" %}

{% block body_attributes %} class="bg-black
text-white mt-0" {% endblock %}

{% block styles %}
    <style>
        html,
        body {
            overflow-x: hidden;
            width: 100% !important;
        }
    </style>
{% endblock %}

{% block body %}
<nav
  id="navScroll"
  class="navbar navbar-dark bg-black fixed-top px-vw-5"
  tabindex="0">
  <div class="container">
    <a
      class="navbar-brand pe-md-4 fs-4 col-12 col-md-auto text-center"
      href="/">
      <span class="ms-md-1 mt-1 fw-bolder me-md-5">Vitrine</span>
    </a>

    <ul
      class="navbar-nav mx-auto mb-2 mb-lg-0 list-group list-group-horizontal">
      <li class="nav-item">
        <a
          class="nav-link fs-5"
          href="{{ url_for('auth.login') }}"
          aria-label="Login to vitrine dashboard">
          Login
        </a>
      </li>
      <li class="nav-item">
        <a
          class="nav-link fs-5"
          href="{{ url_for('auth.register') }}"
          aria-label="Become a vitriner">
          Register
        </a>
      </li>
    </ul>
  </div>
</nav>

<main>
  {% block content %}
  {% endblock %}
</main>

<footer class="bg-black border-top border-dark">
  <div class="container py-vh-4 text-secondary fw-lighter">
    <div class="row">
      <div class="col-12 col-lg-5 py-4 text-center text-lg-start">
        <a
          class="navbar-brand pe-md-4 fs-4 col-12 col-md-auto text-center fw-bolder"
          href="/">
          <span class="ms-md-1 mt-1 fw-bolder me-md-5">Vitrine</span>
        </a>
      </div>
      <div class="col border-end border-dark">
        <span class="h6">Go to</span>
        <ul class="nav flex-column">
          <li class="nav-item">
            <a href="{{ url_for('general.brand', handle='vitrine') }}"
              class="link-fancy link-fancy-light"
              target="_blank">Our page</a>
          </li>
          <li class="nav-item">
            <a href="{{ url_for('auth.login') }}" class="link-fancy link-fancy-light">Login</a>
          </li>
          <li class="nav-item">
            <a href="{{ url_for('auth.register') }}" class="link-fancy link-fancy-light">
              Register
            </a>
          </li>
        </ul>
      </div>
      <div class="col border-end border-dark">
        <span class="h6">Project</span>
        <ul class="nav flex-column">
          <li class="nav-item">
            <a href="https://github.com/sixtusagbo/vitrine"
              class="link-fancy link-fancy-light"
              target="_blank">GitHub Repo</a>
          </li>
          <li class="nav-item">
            <a href="https://trello.com/b/17TmBcq8/portfolio-project" class="link-fancy link-fancy-light">Trello</a>
          </li>
        </ul>
      </div>
      <div class="col" id="connect_with_me">
        <span class="h6">Let's Connect</span>
        <ul class="nav flex-column">
          <li class="nav-item">
            <a
              href="https://github.com/sixtusagbo"
              class="link-fancy link-fancy-light"
              target="_blank">
              GitHub
            </a>
          </li>
          <li class="nav-item">
            <a
              href="https://twitter.com/sixtusagbo"
              class="link-fancy link-fancy-light"
              target="_blank">
              Twitter
            </a>
          </li>
          <li class="nav-item">
            <a
              href="https://www.linkedin.com/in/sixtusagbo"
              class="link-fancy link-fancy-light"
              target="_blank">
              LinkedIn
            </a>
          </li>
          <li class="nav-item">
            <a
              href="https://g.dev/sixtusagbo"
              class="link-fancy link-fancy-light"
              target="_blank">
              Google Dev
            </a>
          </li>
          <li class="nav-item mb-3">
            <a
              href="mailto:miracleagbosixtus@gmail.com"
              class="link-fancy link-fancy-light"
              target="_blank">
              Email
            </a>
          </li>
        </ul>
      </div>
  </div>
  <div class="container text-center small py-vh-2 border-top border-dark">
    &copy; <span class="text-light">Vitrine</span> 2023 | Developed by <span class="text-light">Sixtus Agbo Miracle</span>
  </div>
</footer>
{% endblock %}